package obligatorio.JKOC.ui;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import obligatorio.JKOC.dominio.Agenda;
import obligatorio.JKOC.dominio.Contacto;
import obligatorio.JKOC.dominio.Telefono;
import obligatorio.JKOC.dominio.TipoContacto;
import obligatorio.JKOC.dominio.TipoTelefono;
import obligatorio.JKOC.dominio.Jugador;
import obligatorio.JKOC.exceptions.ContactoInvalidoException;
import obligatorio.JKOC.exceptions.TelefonoInvalidoException;
import obligatorio.JKOC.controllers.AgendaVistaControlador;

/**
 *
 * @author ddauser
 */
public class DialogoAgenda extends DialogoBase implements AgendaVista {

    private final AgendaVistaControlador controlador;

    /**
     * Separo en este string "criterio" el valor de lo que hay en el TextBox de
     * criterio de busqueda, solo cuando se hace click en el boton "Buscar"
     * Notar que el metodo buscar() se reusa, pero no debe tener en cuenta lo
     * que este en el TextBox si no se presiono "Buscar".
     */
    private String criterio;

    public DialogoAgenda(java.awt.Frame parent, boolean modal, Jugador usuario) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        controlador = new AgendaVistaControlador(this, usuario.getAgenda());
        this.criterio = tCriterioBusqueda.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cTiposContacto = new javax.swing.JComboBox();
        tNombre = new javax.swing.JTextField();
        tTelefono = new javax.swing.JTextField();
        bCrear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lContactos = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tCriterioBusqueda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bBuscar = new javax.swing.JButton();
        lResultados = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tDetalle = new javax.swing.JTextArea();
        bLogout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cTiposTelefono = new javax.swing.JComboBox();
        bNuevoGrupo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bienenido a la agenda");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        bCrear.setText("Crear");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        lContactos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lContactosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lContactos);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tipo de contacto:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Telefono:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Buscar:");

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        lResultados.setForeground(new java.awt.Color(153, 153, 153));
        lResultados.setText("Mostrando todos los contactos");

        tDetalle.setEditable(false);
        tDetalle.setColumns(20);
        tDetalle.setForeground(new java.awt.Color(153, 153, 153));
        tDetalle.setRows(3);
        jScrollPane2.setViewportView(tDetalle);

        bLogout.setText("Logout");
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Tipo de telefono:");

        bNuevoGrupo.setText("Nuevo Grupo");
        bNuevoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 26, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tNombre)
                            .addComponent(cTiposContacto, 0, 221, Short.MAX_VALUE)
                            .addComponent(cTiposTelefono, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tTelefono, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bLogout)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tCriterioBusqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bBuscar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addComponent(lResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(bNuevoGrupo)
                    .addContainerGap(732, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTiposContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tCriterioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(bBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cTiposTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addComponent(bCrear)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bLogout)
                        .addGap(29, 29, 29)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(324, Short.MAX_VALUE)
                    .addComponent(bNuevoGrupo)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        this.crearContacto();
    }//GEN-LAST:event_bCrearActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        this.criterio = tCriterioBusqueda.getText();
        this.buscar();
    }//GEN-LAST:event_bBuscarActionPerformed

    private void lContactosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lContactosValueChanged
        this.contactoSeleccionado();
    }//GEN-LAST:event_lContactosValueChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        cerrarVentana();
    }//GEN-LAST:event_formWindowClosed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        this.dispose();
    }//GEN-LAST:event_bLogoutActionPerformed

    private void bNuevoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoGrupoActionPerformed
        controlador.mostrarVistaNuevoGrupo();
    }//GEN-LAST:event_bNuevoGrupoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCrear;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bNuevoGrupo;
    private javax.swing.JComboBox cTiposContacto;
    private javax.swing.JComboBox cTiposTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList lContactos;
    private javax.swing.JLabel lResultados;
    private javax.swing.JTextField tCriterioBusqueda;
    private javax.swing.JTextArea tDetalle;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tTelefono;
    // End of variables declaration//GEN-END:variables

    private void crearContacto() {
        Contacto nuevoContacto = new Contacto();
        nuevoContacto.setTipoContacto((TipoContacto) cTiposContacto.getSelectedItem());
        nuevoContacto.setNombre(tNombre.getText());

        Telefono telefono = new Telefono();
        telefono.setNumero(tTelefono.getText());
        telefono.setTipoTelefono((TipoTelefono) cTiposTelefono.getSelectedItem());

        nuevoContacto.setTelefono(telefono);
        controlador.crearContacto(nuevoContacto);

    }

    private void buscar() {
        controlador.buscarContacto(criterio);
    }

    private void contactoSeleccionado() {
        Contacto contactoSeleccionado = (Contacto) lContactos.getSelectedValue();
        controlador.contactoSeleccionado(contactoSeleccionado);
    }

    private void cerrarVentana() {
        controlador.logout();
    }

    @Override
    public void mostrarTiposDeContacto(ArrayList<TipoContacto> tipos) {
        for (TipoContacto t : tipos) {
            cTiposContacto.addItem(t);
        }
    }

    @Override
    public void mostrarTiposDeTelefno(ArrayList<TipoTelefono> tipos) {
        for (TipoTelefono t : tipos) {
            cTiposTelefono.addItem(t);
        }
    }

    @Override
    public void mostrarContactos(ArrayList<Contacto> contactos) {
        int cantidadDeContactos = 0;
        if (!contactos.isEmpty()) {
            lContactos.setListData(contactos.toArray());
            cantidadDeContactos = contactos.size();
        } else {
            lContactos.setListData(new ArrayList<Contacto>().toArray());
        }
        lResultados.setText(String.format("Mostrando %d contactos.", cantidadDeContactos));
    }

    @Override
    public void mostrarDetalleContacto(Contacto contacto) {
        if (contacto == null) {
            tDetalle.setText("");
        } else {
            tDetalle.setText(String.format("Tipo de contacto: %s\nNombre: %s\nTipo Telefono: %s\nTelefono: %s",
                    contacto.getTipoContacto().getNombre(),
                    contacto.getNombre(),
                    contacto.getTelefono().getTipoTelefono().getNombre(),
                    contacto.getTelefono().getNumero()));
        }
    }

    @Override
    public void mostrarResumenDeInformacion(Agenda agenda) {
        this.setTitle(String.format("Mostrando agenda de %s (%d contactos en la agenda)", agenda.getUsuario().getNombre(), agenda.getCantidadContactos()));
    }

    @Override
    public void mostrarDialogoNuevoGrupoDeContactos(Agenda agenda) {
        new DialogoNuevoGrupoDeContactos(null, false, agenda).setVisible(true);

    }
}
