/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package obligatorio.JKOC.ui;

import java.util.ArrayList;
import obligatorio.JKOC.dominio.Agenda;
import obligatorio.JKOC.dominio.Contacto;
import obligatorio.JKOC.dominio.Grupo;
import obligatorio.JKOC.controllers.NuevoGrupoDeContactosVistaControlador;

/**
 *
 * @author fadavanc
 */
public class DialogoNuevoGrupoDeContactos extends DialogoBase implements NuevoGrupoDeContactosVista {

    private final NuevoGrupoDeContactosVistaControlador controlador;

    /**
     * Creates new form DialogoNuevoGrupoDeContactos
     */
    public DialogoNuevoGrupoDeContactos(java.awt.Frame parent, boolean modal, Agenda agenda) {
        super(parent, modal);
        initComponents();
        controlador = new NuevoGrupoDeContactosVistaControlador(agenda, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNombreDeGrupo = new javax.swing.JLabel();
        tNombreDelGrupo = new javax.swing.JTextField();
        jlistGrupos = new javax.swing.JScrollPane();
        jlistContactos = new javax.swing.JList();
        jlistGrupos1 = new javax.swing.JScrollPane();
        jGrupos = new javax.swing.JList();
        jbCrearGrupo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lNombreDeGrupo.setText("Nombre del Grupo:");

        jlistGrupos.setViewportView(jlistContactos);

        jGrupos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlistGrupos1.setViewportView(jGrupos);

        jbCrearGrupo.setText("Crear Grupo");
        jbCrearGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lNombreDeGrupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tNombreDelGrupo)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlistGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jbCrearGrupo)
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jlistGrupos1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(223, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombreDeGrupo)
                    .addComponent(tNombreDelGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlistGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCrearGrupo)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jlistGrupos1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCrearGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearGrupoActionPerformed
        controlador.crearGrupo(tNombreDelGrupo.getText(), jlistContactos.getSelectedValuesList());
    }//GEN-LAST:event_jbCrearGrupoActionPerformed

    @Override
    public void mostrarContactos(ArrayList<Contacto> contactos) {
        jlistContactos.setListData(contactos.toArray());
    }

    @Override
    public void mostrarGrupos(ArrayList<Grupo> grupos) {
        ArrayList<String> items = new ArrayList<>();
        grupos.forEach(g -> items.add(g.getNombre() + " (" + g.getCantidadDeContactos() + ")"));
        this.jGrupos.setListData(items.toArray());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jGrupos;
    private javax.swing.JButton jbCrearGrupo;
    private javax.swing.JList jlistContactos;
    private javax.swing.JScrollPane jlistGrupos;
    private javax.swing.JScrollPane jlistGrupos1;
    private javax.swing.JLabel lNombreDeGrupo;
    private javax.swing.JTextField tNombreDelGrupo;
    // End of variables declaration//GEN-END:variables
}
